### ISSUE TITLE
ImportError: No module named networkx

### ISSUE THREAD

**Issue by kondoruy** [tvwenger/maxfield#1]
C:\Python27\maxfield-master>python makePlan.py -b 2 Example.csv out/ output.pkl
Traceback (most recent call last):
  File "makePlan.py", line 43, in <module>
    import networkx as nx
ImportError: No module named networkx

**Comment by tvwenger** [comment]
You need to install the package dependencies as stated in the Readme. 

"You'll need Python (I've got 2.7) as well as networkx, numpy, and matplotlib."
