### ISSUE TITLE
how can i solve this error

### ISSUE THREAD

**Issue by ghost** [tvwenger/maxfield#15]
root@VM-104-3-ubuntu:~/maxfield-master# python makePlan.py --help
Traceback (most recent call last):
  File "makePlan.py", line 43, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
ImportError: No module named compat.numpy

Python 2.7.12
Requirement already satisfied: distribute>=0.7.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: matplotlib>=1.3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: networkx==1.8.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: numpy>=1.8.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: docopt>=0.6.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pandas>=0.14.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pebble>=3.1.14 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python2.7/dist-packages (from distribute>=0.7.3->-r requirements.txt (line 1))
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))
Requirement already satisfied: functools32 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))
Requirement already satisfied: six>=1.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))
Requirement already satisfied: subprocess32 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->-r requirements.txt (line 2))

**Comment by tvwenger** [comment]
Haven't seen that problem before. What version of pandas are you running?

**Comment by ghost** [comment]
Requirement already satisfied: pandas>=0.14.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))

**Comment by tvwenger** [comment]
Ok, I see that your version of pandas is >= 0.14.1, but what version are you running?

**Comment by ghost** [comment]
pandas-0.19.2-cp27-cp27mu-manylinux1_x86_64.whl

**Comment by ghost** [comment]
I‘m switch to another source to reinstall pandas.

**Comment by tvwenger** [comment]
Alright, this just seems like a problem with your installation of pandas. I just upgraded pandas to 0.19.2 and had no problem. Closing this issue.

**Comment by ghost** [comment]
I'm stil running into a problem.
python makePlan.py -n 1 portal.csv -d out/ -f output.pkl
Traceback (most recent call last):
  File "makePlan.py", line 48, in <module>
    from pebble import process, TimeoutError # to handle timeout
  File "/usr/local/lib/python2.7/dist-packages/pebble/process/__init__.py", line 3, in <module>
    from pebble.process.pool import Pool
  File "/usr/local/lib/python2.7/dist-packages/pebble/process/pool.py", line 24, in <module>
    from pebble import thread
  File "/usr/local/lib/python2.7/dist-packages/pebble/thread/__init__.py", line 3, in <module>
    from pebble.thread.pool import Pool
  File "/usr/local/lib/python2.7/dist-packages/pebble/thread/pool.py", line 21, in <module>
    from pebble.pool import ERROR, RUNNING, SLEEP_UNIT
ImportError: cannot import name ERROR



cycler==0.10.0
dnspython==1.12.0
docopt==0.6.2
functools32==3.2.3.post2
futures==3.0.5
matplotlib==2.0.0
networkx==1.8.1
numpy==1.12.0
pandas==0.19.2
Pebble==4.1.0
pycrypto==2.6.1
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2016.10
six==1.10.0
subprocess32==3.2.7

**Comment by ghost** [comment]
i guess there is something wrong with Pebble? @tvwenger

**Comment by tvwenger** [comment]
This looks like a problem with pebble, not with Maxfield.

**Comment by pwiecz** [comment]
I have the same problem ("ImportError: cannot import name ERROR") on my computer.
As a workaround I've just removed the offending import from the makePlan.py because I don't use the timeout feature.

**Comment by ghost** [comment]
@pwiecz 解决了。
我用了100+的portal来规划多重，然后网站提示说耗时太久，拒绝了，于是我就放到自己的vps上运行了。
运行的时间的确挺长。
