### ISSUE TITLE
Error: cannot import name process

### ISSUE THREAD

**Issue by franckentien** [tvwenger/maxfield#24]
I have copy the file on my computer and install the dependency 
when i run the command : `python makePlan.py --help` i got an error :

```
Traceback (most recent call last):
  File "makePlan.py", line 48, in <module>
    from pebble import process, TimeoutError # to handle timeout
ImportError: cannot import name process
```

i run the script with python 2.7.14+ on kali linux

**Comment by tvwenger** [comment]
Fixed requirements.txt file
https://github.com/tvwenger/maxfield/commit/bbe8f1c4c32703352e8bc8c90373ba0d5115fc4e

**Comment by franckentien** [comment]
solved thanks, 
I need also to run this command: `pip install --upgrade numpy scipy pandas`
