### ISSUE TITLE
Make KML instead of png plots

### ISSUE THREAD

**Issue by johnd0e** [tvwenger/maxfield#26]
Often those png images are too small to distinguish links/numbers at dense areas.
Instead of rendering `png` I propose to make output to [`KML`](https://developers.google.com/kml/)-file, which could be visualized with any scale/zoom, using some GIS-software, e.g. Google Earth.

Also, as stated at http://www.ingress-maxfield.com/:
> A bottleneck in the plan generation was the creation of the link-by-link images

In case of KML it's easy to incorporate all sequence of linking, in same raw-`xml` file, and thus all the linking story could be browsed step by step.

P.S.
All additional data tables also could be included in `KML`, but it is much less important than links plots.

**Comment by tvwenger** [comment]
The plots are really just fun to look at, and not useful for actual execution of the plan. I'm going to close this for now, but if there is any other interest then I could consider adding this feature.

**Comment by johnd0e** [comment]
> The plots are really just fun to look at, and not useful for actual execution of the plan.

Well, plots would be really useful BEFORE actual execution, just to get general idea of what should be done.
But in current form they are even not fun.
