### ISSUE TITLE
New install - pebble not included

### ISSUE THREAD

**Issue by pvuchetich** [tvwenger/maxfield#5]
It looks like pebble needs to be included in the requirements.txt file as a dependency.
pebble>=3.1.14

my solution for one installation: 
%sudo pip install pebble

This installed Pebble (3.1.14)

The error message below is when running the example script the first time.
After manually installing pebble, the script completed without error, and generated the expected output.  I do not know what the absolute minimum version of pebble that is required, so I referenced the version pip installed for me on 3/15/2016.

Reference output:
% python makePlan.py -n 4 EXAMPLE.portals -d out/ -f output.pkl
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "makePlan.py", line 48, in <module>
    from pebble import process, TimeoutError # to handle timeout
ImportError: No module named pebble

**Comment by pvuchetich** [comment]
Adding "pebble>=3.1.14" to the requirements.txt file resolved the issue.

Validation steps:
1. edit requirements.txt, adding "pebble>=3.1.14" at the end,
2. %sudo pip uninstall pebble
3. %python makePlan.py -n 4 EXAMPLE.portals -d out/ -f output.pkl
Traceback (most recent call last):
  File "makePlan.py", line 48, in <module>
    from pebble import process, TimeoutError # to handle timeout
ImportError: No module named pebble
1. sudo pip install -r requirements.txt 
2. python makePlan.py -n 4 EXAMPLE.portals -d out/ -f output.pkl
   --> success

**Comment by tvwenger** [comment]
Thanks! I just updated the requirements file.
